### ISSUE TITLE
How can i reslove the problem i met when i  installed sgx-gmp?

### ISSUE THREAD

**Issue by zhq0918** [intel/sgx-gmp#2]
I installed the sgx-gmp by flow steps:
1、./sgx-configure
2、make
3、make install
but when i executed the 2 step, I met some problem as flows:
In file included from nextprime.c:56:0:
gmp-impl.h:292:3: error: expected identifier or ‘(’ before ‘do’
   do {     \
   ^
/opt/intel/sgxsdk/include/tlibc/string.h:65:22: note: in expansion of macro ‘memset’
 void * _TLIBC_CDECL_ memset(void *, int, size_t);
                      ^
gmp-impl.h:298:5: error: expected identifier or ‘(’ before ‘while’
   } while (0)
     ^
/opt/intel/sgxsdk/include/tlibc/string.h:65:22: note: in expansion of macro ‘memset’
 void * _TLIBC_CDECL_ memset(void *, int, size_t);
                      ^
Makefile:1259: recipe for target 'libsgx_tgmp_a-nextprime.o' failed
make[2]: *** [libsgx_tgmp_a-nextprime.o] Error 1
make[2]: Leaving directory '/opt/sgx_main/sgx-gmp'
Makefile:1350: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/sgx_main/sgx-gmp'
Makefile:1024: recipe for target 'all' failed
make: *** [all] Error 2

how can i resolved the problem?  Did i install the sgx-gmp steps error?

**Comment by jmechalas** [comment]
Thanks. I am seeing this as well, and it appears to be related to the SGX SDK version. sgx-gmp was built and tested against 2.3.1. I'll dig into this and see what changed that caused this to break.

**Comment by jmechalas** [comment]
A change in the SGX SDK starting with version 2.4 introduced a dependency on the trusted service library in certain circumstances, and the autoconf macros weren't adding that to the library list when testing for function availability. This, in turn, caused sgx-gmp to erroneously believe memset was not present (since the build test failed on an undefined symbol), and that resulted in a broken macro that led to this error.

I've pushed out an update that fixes this, and was able to build successfully against SGX SDK 2.4 and 2.5. Please test it out and let me know how it goes.

**Comment by zhq0918** [comment]
hi,@jmechalas,I have download the new version, and after i executed the sgx-configure script, i make and make install success. thanks a lot.

**Comment by zhq0918** [comment]
@jmechalas , but after make success, i make check failed.thanks.

**Comment by jmechalas** [comment]
`make check` isn't supported, per the README. It would require writing enclave-ized versions of the test programs.

**Comment by zhq0918** [comment]
ok, thanks @jmechalas
